### ISSUE TITLE
Large jpg error

### ISSUE THREAD

**Issue by XaviAure** [glenrobson/iiif-tiler#14]
Hi Glen
I have been trying to use the tiler for large jpg images (65000 x 40335) but it keeps giving me errors. The largest size I managed to run was 30000 px. Is there a maximum size the tiler can run? Thanks for your help.

Zoom level 5
Exception in thread "main" java.lang.IllegalArgumentException: width*height > Integer.MAX_VALUE!
        at javax.imageio.ImageReader.getDestination(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at uk.co.gdmrdigital.iiif.image.IIIFImage.loadImage(IIIFImage.java:23)
        at uk.co.gdmrdigital.iiif.image.IIIFImage.<init>(IIIFImage.java:18)
        at uk.co.gdmrdigital.iiif.image.Tiler.createImages(Tiler.java:177)
        at uk.co.gdmrdigital.iiif.image.Tiler.main(Tiler.java:234)

**Comment by XaviAure** [comment]
Thanks for looking into it. I know about the 65k limit, the images were already resized to fall below that limit, that is why I thought there was some other error going on. 
Thanks again.
