### ISSUE TITLE
Negative or zero width error

### ISSUE THREAD

**Issue by martimpassos** [glenrobson/iiif-tiler#33]
Hi Glen, this has worked like a charm so far, but now I'm getting the following error for an apparently perfectly fine image:
```
Exception in thread "main" java.awt.image.RasterFormatException: negative or zero width
        at java.desktop/java.awt.image.Raster.<init>(Raster.java:1192)
        at java.desktop/java.awt.image.WritableRaster.<init>(WritableRaster.java:129)
        at java.desktop/sun.awt.image.SunWritableRaster.<init>(SunWritableRaster.java:129)
        at java.desktop/sun.awt.image.ByteComponentRaster.<init>(ByteComponentRaster.java:155)
        at java.desktop/sun.awt.image.ByteInterleavedRaster.<init>(ByteInterleavedRaster.java:192)
        at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1256)
        at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
        at uk.co.gdmrdigital.iiif.image.Tiler.generateScaleTiles(Tiler.java:126)
        at uk.co.gdmrdigital.iiif.image.Tiler.generateTiles(Tiler.java:63)
        at uk.co.gdmrdigital.iiif.image.Tiler.generateTiles(Tiler.java:54)
        at uk.co.gdmrdigital.iiif.image.Tiler.createImage(Tiler.java:187)
        at uk.co.gdmrdigital.iiif.image.Tiler.createImages(Tiler.java:225)
        at uk.co.gdmrdigital.iiif.image.Tiler.main(Tiler.java:320)
```
Any ideas? The image is available [here](https://forum.jstor.org/assets/33514196/representation-view) if you want to test it.

**Comment by glenrobson** [comment]
This works in the latest version.
